### ISSUE TITLE
Allow to pass custom parameters to Busboy

### ISSUE THREAD

**Issue by dgadelha** [cristovao-trevisan/express-multipart-file-parser#1]
It'd be nice to allow passing custom parameters to Busboy (like, to define file size limit).

And, a HUGE THANKS for this library. This was the solution after almost 3 hours of search and struggle.

**Comment by cristovao-trevisan** [comment]
Thanks for the thanks, not entirely my solution though, just followed an answer on StackOverflow.
Also, just added the requested options, see the new README for more information.
