### ISSUE TITLE
I still get `missing multipart field` even after installing busboy for Cloud Functions

### ISSUE THREAD

**Issue by adriaanbalt** [cristovao-trevisan/express-multipart-file-parser#4]
Firstly, thanks.

I'm trying to upload files through GraphQL to a Firebase Cloud Storage.

I've been using this in conjunction with Firebase Cloud Functions and an Apollo GraphQL Express Server.  I am still getting the following error:
`BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).` with a `400 bad request`

Here is my cURL
```bash
curl 'http://localhost:5000/my-app/us-central1/api' -H 'accept: */*' -H 'Referer: http://localhost:3001/' -H 'Origin: http://localhost:3001' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'Sec-Fetch-Mode: cors' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBEn54vJZH3hg1sBm' --data-binary $'------WebKitFormBoundaryBEn54vJZH3hg1sBm\r\nContent-Disposition: form-data; name="operations"\r\n\r\n{"operationName":"SingleUpload","variables":{"file":null},"query":"mutation SingleUpload($file: Upload\u0021) {\\n  singleUpload(file: $file) {\\n    filename\\n    mimetype\\n    encoding\\n    __typename\\n  }\\n}\\n"}\r\n------WebKitFormBoundaryBEn54vJZH3hg1sBm\r\nContent-Disposition: form-data; name="map"\r\n\r\n{"1":["variables.file"]}\r\n------WebKitFormBoundaryBEn54vJZH3hg1sBm\r\nContent-Disposition: form-data; name="1"; filename="00n0n_bEJWcIpml9s_600x450.jpg"\r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundaryBEn54vJZH3hg1sBm--\r\n' --compressed
```

My server setup looks like this:

```js
const express = require('express')
const cors = require('cors');
const { ApolloServer } = require('apollo-server-express')
const fileParser = require('express-multipart-file-parser')
const schema = require('./schema')
const resolvers = require('./resolvers')

const app = express();
// cors allows our server to accept requests from different origins
app.use(cors());
app.options('*', cors());
app.use(fileParser)
// setup server
const server = new ApolloServer({
    typeDefs: schema,
    resolvers,
    introspection: true, // so we can access the playground in production reference: https://www.apollographql.com/docs/apollo-server/api/apollo-server/#constructor-options-lt-ApolloServer-gt
    playground: true,
    uploads: {
        // Limits here should be stricter than config for surrounding
        // infrastructure such as Nginx so errors can be handled elegantly by
        // graphql-upload:
        // https://github.com/jaydenseric/graphql-upload#type-processrequestoptions
        maxFileSize: 10000000, // 10 MB
        maxFiles: 1
    },
})
server.applyMiddleware({ app, path: '/', cors: true })
```

I've logged throughout your NPM module and I do get to this part

```js
busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
    let fileBuffer = Buffer.from('')
    file.on('data', (data) => { fileBuffer = Buffer.concat([fileBuffer, data]) })
    console.log('here!!', file, filename)
    console.log('fileBuffer', fileBuffer)
    file.on('end', () => {
    req.files.push({
        fieldname,
        originalname: filename,
        encoding,
        mimetype,
        buffer: fileBuffer,
    })
    console.log('END!', fileBuffer)
    })
})

busboy.on('finish', () => {
    console.log( 'busboy finish')
    next()
})
```

Am I missing some small thing in my setup that I've overlooked?

**Comment by adriaanbalt** [comment]
A bit of digging led me to this.. haven't tried it yet but I'm thinking of doing this instead. https://stackoverflow.com/questions/42775668/firebase-cloud-functions-multipart-form-data

**Comment by cristovao-trevisan** [comment]
It seem it's an issue with the apollo server (I never used GraphQL before). Reading the docs ([here](https://www.apollographql.com/docs/apollo-server/data/file-uploads/)) it seems there is no need to use any extra express middleware for file upload.
Also found [this article](https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675#File-upload-with-schema-param) that says you'll need to install the [graphql-upload middleware](https://github.com/jaydenseric/graphql-upload).

As said at the stackoverflow question you linked, you could upload your file using the firebase web api and them send the path to your server. This is not ideal though

**Comment by cristovao-trevisan** [comment]
Let me know if you get anywhere with this :smiley:

**Comment by adriaanbalt** [comment]
I'll try that extra `graphql-upload middleware` you mentioned and let you know.

I stumbled across using `createUploadLink` here [https://github.com/jaydenseric/apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) although it isn't clear

Here is how I am setting up Apollo Client using the `link` attribute along with above server code:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { ApolloProvider } from 'react-apollo'
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { createUploadLink } from 'apollo-upload-client'
import { Provider } from 'react-redux'
import store, { history } from './Store'
import { ConnectedRouter } from 'react-router-redux'
import App from './App'
import registerServiceWorker from './lib/serviceWorker'
import './index.scss'
import { GRAPHQL_URL} from './constants/graphql'

const uploadLink = createUploadLink({
    uri: GRAPHQL_URL, // Apollo Server is served from port 4000
    headers: {
        "keep-alive": "true"
    }
})
const apolloCache = new InMemoryCache()

const client = new ApolloClient({
    cache: apolloCache,
    link: uploadLink,
    uri: GRAPHQL_URL,
});

ReactDOM.render(
    <ApolloProvider client={client}>
        <Provider store={store}>
            <ConnectedRouter history={history}>
                <App />
            </ConnectedRouter>
        </Provider>
    </ApolloProvider>,
    document.getElementById('root')
)
registerServiceWorker()
```

In your opinion, why is the stackoverflow question I linked  _"not ideal though"_?

**Comment by cristovao-trevisan** [comment]
Not ideal because you'll be dividing your api into two steps (a bad thing
if you follow DDD's principles) .
Plus, if you want an ironclad api, you'll also need to check if the image
was uploaded to the given path. Also need to implement firebase storage
auth rules.
Firebase sdk is also huge (storage alone will add up to 1s to the first
meaningful load in low end devices if you don't handle it using bundle
split)

**Comment by adriaanbalt** [comment]
I agree with your assessment, initially my goal was to send a mutation over _Firebase Cloud Function_ to _GraphQL_ including some textual information along with a _File_ (could be base64).  The file would be uploaded to Firebase Storage and upon completion would be stored within Firebase Firestore (possibly using a [_Transaction_](https://firebase.google.com/docs/firestore/manage-data/transactions) to manage concurrency but I'm still debating this).  Does this approach sound correct to you?

I also ran into [this approach](https://graphql-modules.com/docs/recipes/file-uploads#enabling-uploads-in-apollo-server) which shows that including `uploads` as a property on `ApolloServer` should be sufficient to use without the `graphqlUploadExpress` middleware, which I'm doing as you can see above.

PS: Do you suggest an alternative file storage?  S3?  Although this doesn't solve my issue with sending `multipart/form-data` over Cloud Functions to GraphQL because I'll still need to do that regardless of where store.

**Comment by cristovao-trevisan** [comment]
Don't know the specifics of your application, but I've done that before
(I've used firebase in a few projects). I used the functions trigger to
save the metadata to firestore, the downside is to handle the async
complexity this bring up.

If you use Firestore that's a good approach, I think, otherwise not.

**Comment by cristovao-trevisan** [comment]
Closing as explained in the referenced issue (and possible solution)

**Comment by kurtabela** [comment]
Did you ever solve this issue?
