### ISSUE TITLE
fileParser is not a function 

### ISSUE THREAD

**Issue by AlphaNiner1415** [cristovao-trevisan/express-multipart-file-parser#5]
when I try the destructuring in order to add options I get error "fileParser is not a function"

```
const {fileParser} = require('express-multipart-file-parser')

app.use(fileParser({
    rawBodyOptions: {
        limit: '15mb',
    },
    busboyOptions: {
        limits: {
            fields: 2,
        },
    },
}))
```

**Comment by cristovao-trevisan** [comment]
Try running
```js
const {fileParser} = require('express-multipart-file-parser')
console.log(fileParser)
```

It should return `[Function: fileParser]`. At least it does for me

**Comment by AlphaNiner1415** [comment]
Comes up as undefined, I'm using Express typescript by the way, any difference to be aware of?

**Comment by AlphaNiner1415** [comment]
<img width="891" alt="Screen Shot 2021-01-19 at 17 53 22" src="https://user-images.githubusercontent.com/39154768/105024928-3adf6f00-5a7f-11eb-8a39-ff52eb238827.png">

**Comment by cristovao-trevisan** [comment]
Yes, you need to configure the typescript compiler to accept CommomJS modules, something related to [moduleResolution](https://www.typescriptlang.org/tsconfig#moduleResolution) if I'm not mistaken.
Note that there's no type definitions for this module, so you need to also use the `allowJs` and disable strict typing

**Comment by AlphaNiner1415** [comment]
Ok thanks I'll go give it a try
